export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_MULT_SONGS: "SET_MULT_SONGS",
  SET_NAME: "SET_NAME",
  SET_IMAGE: "SET_IMAGE",
  SET_TIME: "SET_TIME",
  SET_URIS: "SET_URIS"
};